### ISSUE TITLE
Failed to resolve Firebase.Auth.MultiFactorAssertion

### ISSUE THREAD

**Issue by Cellus250** [f-miyu/Plugin.FirebaseAuth#26]
Hi Miyu. Would you have any guidance on the error I am facing?

Following upgrading from 3.1.0 to 4.0.0-pre01, I am getting the compilation error shown below on Droid targeting Android version 10.0 (API Level 29 - Q).

Thank you.

Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Firebase.Auth.MultiFactorAssertion' (defined in assembly 'Plugin.FirebaseAuth, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Firebase.Auth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Firebase.Auth.MultiFactorAssertion
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field)
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---

**Comment by f-miyu** [comment]
@Cellus250 Please try to explicitly install [Xamarin.Firebase.Auth:119.3.1-preview02](https://www.nuget.org/packages/Xamarin.Firebase.Auth/119.3.1-preview02) to your Android project.

**Comment by Cellus250** [comment]
Hi Miyu. Thank you for the response. Sorry for the bother, it seems that it is working now. Some how when I installed  Xamarin.Firebase.Auth:119.3.1-preview02 last night, I ran into the same issue even after rebuilding, cleaning, etc. Must have been a VS/Xamarin issue before. 

Thanks again!
