### ISSUE TITLE
Getting Linker error in release build 

### ISSUE THREAD

**Issue by DnyaneshWarade** [f-miyu/Plugin.FirebaseAuth#32]
Hello @f-miyu ,

First of all, thank you for creating such wonderful plugins for firebase.
I hope you are doing great and keeping safe.

In my project in debug, everything works fine, but in release I am getting linker error as follows -

Severity	Code	Description	Project	File	Line	Suppression State
Error		Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Firebase.Auth.MultiFactorAssertion' (defined in assembly 'Plugin.FirebaseAuth, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Firebase.Auth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Firebase.Auth.MultiFactorAssertion
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field)
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	Oasis.Android

I tried various things in my project to resolve this issue but it is still there.
Also I downloaded the Plugin code and tried to update Xamarin.Firebase.Auth to latest but there also it was giving errors for update.
NU1202: Package Xamarin.Firebase.Auth 120.0.3 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.Firebase.Auth 120.0.3 supports: monoandroid90 (MonoAndroid,Version=v9.0)
NU1202: Package Xamarin.Firebase.Auth 120.0.3 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Package Xamarin.Firebase.Auth 120.0.3 supports: monoandroid90 (MonoAndroid,Version=v9.0)

Can you please help to resolve this issue?

**Comment by angelru** [comment]
If you have MultiDex activated, deactivate it.
Remove nuget that do not have to do with Plugin.FirebaseAuth
