### ISSUE TITLE
Error when archiving android project

### ISSUE THREAD

**Issue by Egehanozsoy** [f-miyu/Plugin.FirebaseAuth#33]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.FirebaseAuth.UserWrapper/<LinkWithProviderAsync>d__28::MoveNext()' in assembly: 'Plugin.FirebaseAuth.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Firebase.FirebaseApp Firebase.Auth.FirebaseUser::Zzc()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	FitterrProject.Android

**Comment by nnovalbos** [comment]
Hi, @Egehanozsoy 

I have the same error. something new?

Thanks

**Comment by Egehanozsoy** [comment]
Hey @nnovalbos , go to your android options and then make sure linking is set to none. After that go to the top and enable Multi-Dexing that fixed it for me.

**Comment by nnovalbos** [comment]
@Egehanozsoy thanks for answering

Do you think it is correct not to use the linker? I will use it temporarily but will try to find some other alternative.
If I find something, I'll let you know

**Comment by Egehanozsoy** [comment]
@nnovalbos Thanks, appreciate it

**Comment by AswinPG** [comment]
Hi @Egehanozsoy @nnovalbos  Have you found a solution ? I am also having this issue

**Comment by nnovalbos** [comment]
Hi @AswinPG ,

when i updated the VS for mac to version 8.10.2 build 17, the error disappeared ....

**Comment by AswinPG** [comment]
> Hi @AswinPG ,
> 
> when i updated the VS for mac to version 8.10.2 build 17, the error disappeared ....

I am having this issue on VS 2019 on windows

**Comment by AswinPG** [comment]
https://github.com/f-miyu/Plugin.FirebaseAuth/pull/34 this fixed the issue for me
